### ISSUE TITLE
SuperHot MVP Roadmap

### ISSUE THREAD

**Issue by vasco-santos** [nftstorage/nftstorage.link#2]
Roadmap

## Sprint 0:
- [x] Technical Design document + Roadmap
- [x] Setup Monorepo #3 
- [x] Bootstrap website project #6 
- [x] Setup CF Pages deployment for website
- [x] Initial support for IPNS https://github.com/nftstorage/nftstorage.link/pull/25
- [x] Get Access to CF R2 #1 
- [x] Setup _dnslink for website https://github.com/nftstorage/nftstorage.link/pull/30

## Sprint 1:
- [x] Landing page design kick off #5
- [x] Add `HasSuperHotAccess` user tag to nft.storage DB https://github.com/nftstorage/nft.storage/pull/1838
- [x] **HTTP API** POST /perma-cache/:url https://github.com/nftstorage/nftstorage.link/issues/29
- [x] **HTTP API** GET /perma-cache https://github.com/nftstorage/nftstorage.link/issues/48
- [x] **HTTP API** GET /perma-cache/status https://github.com/nftstorage/nftstorage.link/issues/55
- [x] **HTTP API** DELETE /perma-cache/:url https://github.com/nftstorage/nftstorage.link/issues/54
- [x] Integrate Gateway until worker bindings in place https://github.com/nftstorage/nftstorage.link/pull/53
- [x] Generate HTTP API Docs https://github.com/nftstorage/nftstorage.link/issues/69

## Sprint 2
- [x] Setup /perma-cache rate limits
- [x] Bootstrap Client library
- [x] Read from gateway #60 
- [x] Setup Metrics https://github.com/nftstorage/nftstorage.link/issues/56
- [x] Front-end nftstorage.link landing page kick off
- [x] Setup status page
- [ ] Client library `PermaCache.put`
- [ ] Client library `PermaCache.list`
- [ ] Client library `PermaCache.delete`
- [ ] Client library `PermaCache.info`

## Follow ups:
- [ ] Client library example
- [ ] IPNS support within gateway race + cache
- [ ] Payment System setup
- [ ] Payment System integration
- [ ] Docs for HTTP API + client
- [ ] Image resizing
- [ ] support other URLs
